// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdKFKX81pN1b08kVloeigAVim4vYD3GJ4',
    appId: '1:725005020954:web:deb199c65081d322b5c6a3',
    messagingSenderId: '725005020954',
    projectId: 'clap-and-view-test',
    authDomain: 'clap-and-view-test.firebaseapp.com',
    storageBucket: 'clap-and-view-test.appspot.com',
    measurementId: 'G-SNVCNLKX47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTZW0XZDZmQXhVghAPXWpbGkkz-QzbvjU',
    appId: '1:725005020954:android:66f7db68640e1a33b5c6a3',
    messagingSenderId: '725005020954',
    projectId: 'clap-and-view-test',
    storageBucket: 'clap-and-view-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAybYw0hhLzlV8_pg6uBkdWSTvyS-RGOds',
    appId: '1:725005020954:ios:5214a7dc62707d24b5c6a3',
    messagingSenderId: '725005020954',
    projectId: 'clap-and-view-test',
    storageBucket: 'clap-and-view-test.appspot.com',
    androidClientId: '725005020954-1h3die4juoh3deke76c14j81lq97p0u3.apps.googleusercontent.com',
    iosClientId: '725005020954-h2i94cbih6qbit2gjk1mn2qfac04v1us.apps.googleusercontent.com',
    iosBundleId: 'com.georgekobylyanskiy.clapAndView',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAybYw0hhLzlV8_pg6uBkdWSTvyS-RGOds',
    appId: '1:725005020954:ios:5214a7dc62707d24b5c6a3',
    messagingSenderId: '725005020954',
    projectId: 'clap-and-view-test',
    storageBucket: 'clap-and-view-test.appspot.com',
    androidClientId: '725005020954-1h3die4juoh3deke76c14j81lq97p0u3.apps.googleusercontent.com',
    iosClientId: '725005020954-h2i94cbih6qbit2gjk1mn2qfac04v1us.apps.googleusercontent.com',
    iosBundleId: 'com.georgekobylyanskiy.clapAndView',
  );
}
